INSERT INTO public.titles (id, name) VALUES (1, 'ЗМС                                                                                                 ');
INSERT INTO public.titles (id, name) VALUES (2, 'МСМК                                                                                                ');
INSERT INTO public.titles (id, name) VALUES (3, 'МС                                                                                                  ');
INSERT INTO public.titles (id, name) VALUES (4, 'КМС                                                                                                 ');
INSERT INTO public.titles (id, name) VALUES (5, '1 сп.р.                                                                                             ');
INSERT INTO public.titles (id, name) VALUES (6, '2 сп.                                                                                               ');
INSERT INTO public.titles (id, name) VALUES (7, '3 сп.                                                                                               ');
INSERT INTO public.titles (id, name) VALUES (8, '1 юн.                                                                                               ');
INSERT INTO public.titles (id, name) VALUES (9, '2 юн.                                                                                               ');
INSERT INTO public.titles (id, name) VALUES (10, 'нет                                                                                                 ');
INSERT INTO public.titles (id, name) VALUES (21, 'ЗТР                                                                                                 ');