INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (83, 'Ненецкий автономный округ                                                                           ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (46, 'Курская область                                                                                     ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (39, 'Калининградская область                                                                             ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (3, 'Республика Бурятия                                                                                  ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (35, 'Вологодская область                                                                                 ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (9, 'Карачаево-Черкесская республика                                                                     ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (23, 'Краснодарский край                                                                                  ', 2);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (77, 'Москва                                                                                              ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (21, 'Чувашская республика                                                                                ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (65, 'Сахалинская область                                                                                 ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (25, 'Приморский край                                                                                     ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (71, 'Тульская область                                                                                    ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (13, 'Республика Мордовия                                                                                 ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (41, 'Камчатский край                                                                                     ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (27, 'Хабаровский край                                                                                    ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (57, 'Орловская область                                                                                   ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (32, 'Брянская область                                                                                    ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (63, 'Самарская область                                                                                   ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (58, 'Пензенская область                                                                                  ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (28, 'Амурская область                                                                                    ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (75, 'Забайкальский край                                                                                  ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (70, 'Томская область                                                                                     ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (86, 'Ханты-Мансийский автономный округ - Югра                                                            ', 6);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (69, 'Тверская область                                                                                    ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (67, 'Смоленская область                                                                                  ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (68, 'Тамбовская область                                                                                  ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (6, 'Республика Ингушетия                                                                                ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (14, 'Республика Саха (Якутия)                                                                            ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (72, 'Тюменская область                                                                                   ', 6);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (37, 'Ивановская область                                                                                  ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (24, 'Красноярский край                                                                                   ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (17, 'Республика Тыва                                                                                     ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (92, 'Севастополь                                                                                         ', 9);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (29, 'Архангельская область                                                                               ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (60, 'Псковская область                                                                                   ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (20, 'Чеченская республика                                                                                ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (44, 'Костромская область                                                                                 ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (78, 'Санкт-Петербург                                                                                     ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (1, 'Республика Адыгея                                                                                   ', 2);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (19, 'Республика Хакасия                                                                                  ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (26, 'Ставропольский край                                                                                 ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (79, 'Еврейская автономная область                                                                        ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (51, 'Мурманская область                                                                                  ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (40, 'Калужская область                                                                                   ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (62, 'Рязанская область                                                                                   ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (73, 'Ульяновская область                                                                                 ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (48, 'Липецкая область                                                                                    ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (55, 'Омская область                                                                                      ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (43, 'Кировская область                                                                                   ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (61, 'Ростовская область                                                                                  ', 2);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (47, 'Ленинградская область                                                                               ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (56, 'Оренбургская область                                                                                ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (4, 'Республика Алтай                                                                                    ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (7, 'Кабардино-Балкарская республика                                                                     ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (12, 'Республика Марий Эл                                                                                 ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (33, 'Владимирская область                                                                                ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (54, 'Новосибирская область                                                                               ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (66, 'Свердловская область                                                                                ', 6);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (30, 'Астраханская область                                                                                ', 2);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (53, 'Новгородская область                                                                                ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (22, 'Алтайский край                                                                                      ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (36, 'Воронежская область                                                                                 ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (49, 'Магаданская область                                                                                 ', 4);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (45, 'Курганская область                                                                                  ', 6);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (11, 'Республика Коми                                                                                     ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (31, 'Белгородская область                                                                                ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (8, 'Республика Калмыкия                                                                                 ', 2);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (16, 'Республика Татарстан                                                                                ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (38, 'Иркутская область                                                                                   ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (2, 'Республика Башкортостан                                                                             ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (89, 'Ямало-Ненецкий автономный округ                                                                     ', 6);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (15, 'Республика Северная Осетия — Алания                                                                 ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (50, 'Московская область                                                                                  ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (59, 'Пермский край                                                                                       ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (74, 'Челябинская область                                                                                 ', 6);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (10, 'Республика Карелия                                                                                  ', 3);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (5, 'Республика Дагестан                                                                                 ', 8);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (52, 'Нижегородская область                                                                               ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (34, 'Волгоградская область                                                                               ', 2);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (42, 'Кемеровская область                                                                                 ', 5);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (64, 'Саратовская область                                                                                 ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (91, 'Республика Крым                                                                                     ', 9);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (76, 'Ярославская область                                                                                 ', 1);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (18, 'Удмуртская республика                                                                               ', 7);
INSERT INTO public.rf_subjects (id, name, rf_fo_id) VALUES (87, 'Чукотский автономный округ                                                                          ', 4);