INSERT INTO public.race_type (id, name, id_vid) VALUES (1, 'гонка - Классик                                   ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (2, 'гонка - Крузер                                    ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (3, 'гонка на время                                    ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (4, 'эстафета                                          ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (5, 'дерт                                              ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (6, 'парк                                              ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (7, 'рампа                                             ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (8, 'флэт                                              ', 4);
INSERT INTO public.race_type (id, name, id_vid) VALUES (9, 'байкер - кросс 4-х                                ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (10, 'велокросс                                         ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (11, 'кросс-кантри                                      ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (12, 'кросс - кантри марафон                            ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (13, 'кросс - кантри гонка с выбыванием                 ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (14, 'гонка в гору                                      ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (15, 'многодневная гонка                                ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (16, 'скоростной спуск                                  ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (17, 'триал - 20                                        ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (18, 'триал - 26                                        ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (19, 'триал командный - 20                              ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (20, 'триал командный - 26                              ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (21, 'эстафета                                          ', 3);
INSERT INTO public.race_type (id, name, id_vid) VALUES (22, 'гит с ходу 200 м                                  ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (23, 'гит с ходу 500 м                                  ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (24, 'гит с ходу 1000 м                                 ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (25, 'гит с ходу 1000 м (парами)                        ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (26, 'гит с места 200 м                                 ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (27, 'гит с места 500 м                                 ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (28, 'гит с места 1000 м                                ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (29, 'гит с места 1000 м (парами)                       ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (30, 'гонка за лидером                                  ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (31, 'гонка по очкам                                    ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (32, 'гонка по очкам - многодневная                     ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (33, 'гонка с выбыванием                                ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (34, 'индивидуальная гонка преследования 2 км           ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (35, 'индивидуальная гонка преследования 3 км           ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (36, 'индивидуальная гонка преследования 4 км           ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (37, 'командная гонка преследования 2 км                ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (38, 'командная гонка преследования 3 км                ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (39, 'командная гонка преследования 4 км                ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (40, 'парная гонка преследования 2 км                   ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (41, 'парная гонка преследования 3 км                   ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (42, 'парная гонка преследования 4 км                   ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (43, 'спринт                                            ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (44, 'командный спринт                                  ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (45, 'кейрин                                            ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (46, 'мэдисон                                           ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (47, 'мэдисон - многодневная гонка                      ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (48, 'омниум                                            ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (49, 'скретч                                            ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (50, 'тандем                                            ', 2);
INSERT INTO public.race_type (id, name, id_vid) VALUES (51, 'индивидуальная гонка на время                     ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (52, 'индивидуальная гонка на время 5 км                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (53, 'индивидуальная гонка на время 10 км               ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (54, 'индивидуальная гонка на время 15 км               ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (55, 'индивидуальная гонка на время 20 км               ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (56, 'индивидуальная гонка на время 25 км               ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (57, 'индивидуальная гонка на время 50 км               ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (58, 'индивидуальная гонка на время в гору 10 км        ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (59, 'индивидуальная гонка на время в гору 15 км        ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (60, 'групповая гонка                                   ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (61, 'групповая гонка до 100 км                         ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (62, 'групповая гонка до 120 км                         ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (63, 'групповая гонка до 170 км                         ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (64, 'групповая гонка 180+ км                           ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (65, 'групповая горная гонка                            ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (66, 'командная гонка                                   ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (67, 'многодневная гонка                                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (68, 'парная гонка 25 км                                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (69, 'парная гонка 50 км                                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (70, 'парная гонка 75 км                                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (71, 'парная гонка 100 км                               ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (72, 'критериум 20-40 км                                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (73, 'критериум 50-60 км                                ', 1);
INSERT INTO public.race_type (id, name, id_vid) VALUES (74, 'критериум 70-80 км                                ', 1);