INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (2, 'гонка - Крузер                                    ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (3, 'гонка на время                                    ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (4, 'эстафета                                          ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (5, 'дерт                                              ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (6, 'парк                                              ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (7, 'рампа                                             ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (8, 'флэт                                              ', 4, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (10, 'велокросс                                         ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (14, 'гонка в гору                                      ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (15, 'многодневная гонка                                ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (17, 'триал - 20                                        ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (18, 'триал - 26                                        ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (19, 'триал командный - 20                              ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (20, 'триал командный - 26                              ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (21, 'эстафета                                          ', 3, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (22, 'гит с ходу 200 м                                  ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (24, 'гит с ходу 1000 м                                 ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (25, 'гит с ходу 1000 м (парами)                        ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (26, 'гит с места 200 м                                 ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (27, 'гит с места 500 м                                 ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (28, 'гит с места 1000 м                                ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (29, 'гит с места 1000 м (парами)                       ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (30, 'гонка за лидером                                  ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (32, 'гонка по очкам - многодневная                     ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (35, 'индивидуальная гонка преследования 3 км           ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (36, 'индивидуальная гонка преследования 4 км           ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (38, 'командная гонка преследования 3 км                ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (39, 'командная гонка преследования 4 км                ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (40, 'парная гонка преследования 2 км                   ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (41, 'парная гонка преследования 3 км                   ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (42, 'парная гонка преследования 4 км                   ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (47, 'мэдисон - многодневная гонка                      ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (50, 'тандем                                            ', 2, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (52, 'индивидуальная гонка на время 5 км                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (53, 'индивидуальная гонка на время 10 км               ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (54, 'индивидуальная гонка на время 15 км               ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (55, 'индивидуальная гонка на время 20 км               ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (56, 'индивидуальная гонка на время 25 км               ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (57, 'индивидуальная гонка на время 50 км               ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (58, 'индивидуальная гонка на время в гору 10 км        ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (59, 'индивидуальная гонка на время в гору 15 км        ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (61, 'групповая гонка до 100 км                         ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (62, 'групповая гонка до 120 км                         ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (63, 'групповая гонка до 170 км                         ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (64, 'групповая гонка 180+ км                           ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (65, 'групповая горная гонка                            ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (67, 'многодневная гонка                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (68, 'парная гонка 25 км                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (69, 'парная гонка 50 км                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (70, 'парная гонка 75 км                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (71, 'парная гонка 100 км                               ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (72, 'критериум 20-40 км                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (73, 'критериум 50-60 км                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (74, 'критериум 70-80 км                                ', 1, null, null);
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (66, 'командная гонка                                   ', 1, 'Team Time Trial                                                                                     ', 'TTT    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (51, 'индивидуальная гонка на время                     ', 1, 'Individual Time Trial                                                                               ', 'ITT    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (23, 'гит с ходу 500 м                                  ', 2, 'Time Trial                                                                                          ', 'KT     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (60, 'групповая гонка                                   ', 1, 'Individual Road Race                                                                                ', 'IRR    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (46, 'мэдисон                                           ', 2, 'Madison                                                                                             ', 'MA     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (1, 'гонка - Классик                                   ', 4, null, 'BMX-IND');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (44, 'командный спринт                                  ', 2, 'Team Sprint                                                                                         ', 'TS     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (31, 'гонка по очкам                                    ', 2, 'Points Race                                                                                         ', 'PR     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (43, 'спринт                                            ', 2, 'Sprint                                                                                              ', 'SP     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (48, 'омниум                                            ', 2, 'Omnium                                                                                              ', 'OM     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (45, 'кейрин                                            ', 2, 'Keirin                                                                                              ', 'KE     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (33, 'гонка с выбыванием                                ', 2, 'Elimination Race                                                                                    ', 'EL     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (34, 'индивидуальная гонка преследования 2 км           ', 2, 'Individual Pursuit                                                                                  ', 'IP     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (11, 'кросс-кантри                                      ', 3, 'Cross-country Olympic                                                                               ', 'XCO    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (13, 'кросс - кантри гонка с выбыванием                 ', 3, 'Cross-country eliminator                                                                            ', 'XCE    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (9, 'байкер - кросс 4-х                                ', 3, '4X                                                                                                  ', '4X     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (16, 'скоростной спуск                                  ', 3, 'Downhill                                                                                            ', 'DHI    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (12, 'кросс - кантри марафон                            ', 3, 'Cross-country marathon                                                                              ', 'XCM    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (79, 'Mass Downhill                                     ', 3, 'Mass Downhill                                                                                       ', 'DHM    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (77, 'Para-Cycling                                      ', 2, 'Para-Cycling                                                                                        ', 'PAR    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (76, 'Olympic Sprint                                    ', 2, 'Olympic Sprint                                                                                      ', 'OS     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (83, 'Cross-country team relay                          ', 3, 'Cross-country team relay                                                                            ', 'XCR    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (84, 'Cross-country stage races                         ', 3, 'Cross-country stage races                                                                           ', 'XCS    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (81, 'Cross-country short circuit                       ', 3, 'Cross-country short circuit                                                                         ', 'XCC    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (82, 'Cross-country point-to-point                      ', 3, 'Cross-country point-to-point                                                                        ', 'XCP    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (78, 'Sprint Ranking                                    ', 2, 'Sprint Ranking                                                                                      ', 'ST     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (80, 'Enduro                                            ', 3, 'Enduro                                                                                              ', 'END    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (85, 'Cross-country stage races                         ', null, 'Cross-country time trial                                                                            ', 'XCT    ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (75, 'Pacing Ranking                                    ', 2, 'Pacing Ranking                                                                                      ', 'ED     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (37, 'командная гонка преследования 2 км                ', 2, 'Team Pursuit                                                                                        ', 'TP     ');
INSERT INTO public.race_type (id, name, id_vid, name_eng, name_short_eng) VALUES (49, 'скретч                                            ', 2, 'Scratch                                                                                             ', 'SH     ');